FROM php:7.3-apache
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y wget \
    && wget -O wordpress.tar.gz https://en-au.wordpress.org/latest-en_AU.tar.gz \
    && tar -xzvf wordpress.tar.gz \
    && mv wordpress/* /var/www/html \
	&& chmod -R 755 wp-content \
	&& chown -R www-data:www-data . \
	&& rm -rf wordpress/ wordpress.tar.gz \
	&& apt-get remove -y wget